export const callAction = (() => {
const sectionCall = document.createElement('section');
sectionCall.setAttribute('class', 'call-to-action text-white text-center');
sectionCall.setAttribute('id', 'contact');
const callOverlay = document.createElement('div')
callOverlay.setAttribute('class', 'overlay');
const callContainer = document.createElement('div');
callContainer.setAttribute('class', 'container');
const callRow = document.createElement('div');
callRow.setAttribute('class', 'row');
const colText = document.createElement('div');
colText.setAttribute('class', 'col-xl-9 mx-auto');
const callText = document.createElement('h2');
callText.setAttribute('class', 'mb-4');
callText.textContent = 'Contact';
const colForm = document.createElement('div');
colForm.setAttribute('class', 'col-md-10 col-lg-8 col-xl-7 mx-auto');
const form = document.createElement('form');
const formRow = document.createElement('div');
formRow.setAttribute('class', 'form-row');
const formCol = document.createElement('div');
formCol.setAttribute('class', 'col-12 col-md-9 mb-2 mb-md-0');
const input = document.createElement('input');
input.setAttribute('type', 'email');
input.setAttribute('class', 'form-control form-control-lg');
input.setAttribute('placeholder', 'Enter your email...');
const colButton = document.createElement('div');
colButton.setAttribute('class', 'col-12 col-md-3');
const button = document.createElement('button');
button.setAttribute('type', 'submit');
button.setAttribute('class', 'btn btn-block btn-lg btn-danger');
button.textContent = 'Get Started';
const mobile = document.createElement('h4');
mobile.setAttribute('class', 'font-weight-bold mt-2');
mobile.innerHTML = `<i class="fas fa-mobile-alt"></i>Enquiries: 09033322xxxxxx`
colButton.appendChild(button);
formCol.appendChild(input);
formRow.appendChild(formCol);
formRow.appendChild(colButton);
form.appendChild(formRow);
colForm.appendChild(form);
colForm.appendChild(mobile);
colText.appendChild(callText);
callRow.appendChild(colText);
callRow.appendChild(colForm);
callContainer.appendChild(callRow);
sectionCall.appendChild(callOverlay);
sectionCall.appendChild(callContainer);
return sectionCall;
})();